;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Dash.Cooldown.Time",DevComment="")
+GameplayTagList=(Tag="Data.Stam",DevComment="")
+GameplayTagList=(Tag="Event.AbilitiesChanged",DevComment="please fix my bug")
+GameplayTagList=(Tag="Event.ActivateAbility.Dash",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Swap",DevComment="")
+GameplayTagList=(Tag="Gameplay.Dash.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.RodentVision.On",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash",DevComment="")
+GameplayTagList=(Tag="Rodent.Crouch.Active",DevComment="")
+GameplayTagList=(Tag="RodentVision.Cooldown",DevComment="")
+GameplayTagList=(Tag="Status.Staminia.Regen",DevComment="")
+GameplayTagList=(Tag="Status.Swap.Regen",DevComment="")

